# ---------- BUILD ----------
FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn -q -e -B -DskipTests dependency:go-offline
COPY src ./src
RUN mvn -q -e -B -DskipTests package

# ---------- RUNTIME ----------
FROM eclipse-temurin:21-jre
WORKDIR /app
# Railway injeta PORT
ENV PORT=8080
ENV JAVA_OPTS="-XX:MaxRAMPercentage=75"
COPY --from=build /app/target/*.jar app.jar

EXPOSE ${PORT}
ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar app.jar --server.port=${PORT}"]
